name: Cima Star Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Fix Dependencies and Namespace
        run: |
          # تحديث مكتبة workmanager اللي عملت مشكلة قبل كده
          flutter pub add workmanager:^0.9.0+3
          flutter pub get
          
          # الكود ده بيدخل جوه مكتبة better_player ويضيف الـ namespace عشان الـ Build ميفشلش
          sed -i 's/android {/android {\n    namespace "com.jhomlala.better_player"/' /home/runner/.pub-cache/hosted/pub.dev/better_player-0.0.84/android/build.gradle

      - name: Generate Launcher Icons
        run: flutter pub run flutter_launcher_icons:main || echo "No launcher icons to generate"

      - name: Build Runner (Generate Models)
        run: flutter pub run build_runner build --delete-conflicting-outputs || echo "No models to generate"

      - name: Build APK (Cima Star)
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Cima-Star-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
